"""Step 4 of the agent pipeline: assemble the final strategy report (Markdown)."""

from datetime import datetime

import pandas as pd

from agent.data_cleaner import CleaningReport
from agent.rfm_engine import RFMResult, SEGMENT_ORDER


class ReportGenerator:
    """Turns the pipeline outputs into a single Markdown strategy report."""

    def build(
        self,
        cleaning: CleaningReport,
        rfm_result: RFMResult,
        summary: pd.DataFrame,
        strategies: dict,
    ) -> str:
        rfm = rfm_result.rfm
        lines = []
        add = lines.append

        add("# RFM Customer Segmentation — Strategy Report")
        add("")
        add(f"*Generated automatically on {datetime.now():%Y-%m-%d %H:%M} "
            f"(analysis snapshot date: {rfm_result.snapshot_date:%Y-%m-%d})*")
        add("")

        # ----- Executive summary -------------------------------------------
        top = summary.sort_values("revenue_share_pct", ascending=False).iloc[0]
        add("## 1. Executive Summary")
        add("")
        add(f"- **{len(rfm):,} customers** analysed across "
            f"**${rfm['monetary'].sum():,.0f}** of revenue.")
        add(f"- **{top['segment']}** is the most valuable segment: "
            f"{top['customer_share_pct']:.1f}% of customers generate "
            f"{top['revenue_share_pct']:.1f}% of revenue.")
        add(f"- Average customer: {rfm['frequency'].mean():.1f} orders, "
            f"${rfm['monetary'].mean():,.0f} lifetime spend, last purchase "
            f"{rfm['recency_days'].mean():.0f} days ago.")
        add("")

        # ----- Data quality -------------------------------------------------
        add("## 2. Data Quality (automated cleaning log)")
        add("")
        for action in cleaning.actions:
            add(f"- {action}")
        add("")

        # ----- Segment table -------------------------------------------------
        add("## 3. Segment Overview")
        add("")
        add("| Segment | Customers | Share | Avg Recency (d) | Avg Freq | "
            "Avg Spend | Revenue Share |")
        add("|---|---|---|---|---|---|---|")
        for _, r in summary.iterrows():
            add(f"| {r['segment']} | {int(r['customers']):,} | "
                f"{r['customer_share_pct']:.1f}% | {r['avg_recency_days']:.0f} | "
                f"{r['avg_frequency']:.1f} | ${r['avg_monetary']:,.0f} | "
                f"{r['revenue_share_pct']:.1f}% |")
        add("")

        # ----- Per-segment strategy ------------------------------------------
        add("## 4. Marketing Strategy by Segment")
        add("")
        for seg in SEGMENT_ORDER:
            if seg not in strategies:
                continue
            s = strategies[seg]
            stats = s["stats"]
            add(f"### {seg}")
            add("")
            add(f"*{stats['customers']:,} customers "
                f"({stats['customer_share_pct']:.1f}%) — "
                f"{stats['revenue_share_pct']:.1f}% of revenue*")
            add("")
            add(f"**Diagnosis.** {s['diagnosis']}")
            add("")
            if s.get("llm_narrative"):
                add(f"**AI strategist's view.** {s['llm_narrative']}")
                add("")
            add(f"**Goal.** {s['goal']}")
            add("")
            add("**Recommended actions:**")
            for action in s["actions"]:
                add(f"- {action}")
            add("")
            add(f"**KPIs to track.** {s['kpi']}")
            add("")

        add("---")
        add("*Report generated by the RFM Segmentation Agent "
            "(data cleaning → RFM scoring → segmentation → strategy).*")
        return "\n".join(lines)
